#!/usr/bin/env sh
node --experimental-repl-await -i -e "ldApi = require('.'); Object.assign(global, ldApi); flat=require('./flat'); itches=require('./itches42b.json'); ldgames=require('./ldgames');ds=ldgames.info['91777'];"
